/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : 2012. 09. 04. (화) 14:30:33 KST
    Created by chero@pantech.com (PS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

/*
Target Model : EF65L

LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8X60_EF65L
machine_is_msm8x60_ef65l() function

MODEM & LINUX User Define is T_EF65L
*/


#define EV10  0x01
#define PT10  0x10
#define PT20  0x11
#define WS10  0x21
#define WS15  0x22
#define WS20  0x23
#define ES10  0x31
#define ES20  0x32
#define TP10  0x41
#define TP20  0x42

#define BOARD_REV   TP20

#define SYS_MODEL_NAME "EF65L"
#define SKY_MODEL_NAME "IM-A820L"

#endif /*BOARD_REV_H*/
